由master向dev同步更改
Wikiplus/Wikiplus pull request #84
Opened 2021-05-25 06:22 UTC by AnYiLin

2021-05-25 15:36 UTC, Last-Order requested changes

2021-05-25 15:36 UTC, Last-Order commented on src/core/page.js
> +        mw.loader.using('mediawiki.user').then(() => {
`mediawiki.user`模块在什么情况下不会默认引入吗？
还有这里的`using`失败的情况要处理一下

2021-05-25 15:36 UTC, Last-Order commented on src/utils/settings.js
> +    static version = "3.0.0";
感觉`version`放在`Settings`模块有点不合适，这个模块还是用来处理用户设置内容的，要不还是放到`Constants`里吧

2021-05-25 15:47 UTC, AnYiLin commented on src/core/page.js
> +        mw.loader.using('mediawiki.user').then(() => {
mw.user不在core里面，即如果在调用之前没有其他脚本引用过的话，直接调用就是undefined。而mw.loader是在core里面的，有window.mw就有它。所以为了确保环境中有这个库，应该先加载一下。mw.loader貌似不会有catch的情况，应该用不上异常处理。

2021-05-25 15:48 UTC, AnYiLin commented on src/utils/settings.js
> +    static version = "3.0.0";
嗯，明天改一下，连同#83的CSS。

2021-05-25 15:52 UTC, Last-Order commented on src/core/page.js
> +        mw.loader.using('mediawiki.user').then(() => {
诶所以说`mw.loader.using`并不涉及网络请求是吗，只是一个模块加载的过程，而这个模块实际上已经默认在页面中存在了？那我没问题了

2021-05-26 04:42 UTC, AnYiLin reviewed
一并把CSS微调了下。

2021-05-27 01:03 UTC, merged