修正编辑按钮监听事件重复注入
Wikiplus/Wikiplus pull request #91
Opened 2021-07-29 13:16 UTC by AnYiLin

受mw.hook影响

2021-07-29 15:02 UTC, Last-Order commented
可以详细解释一下吗

2021-07-29 23:55 UTC, AnYiLin commented
受 https://github.com/Wikiplus/Wikiplus/blob/master/src/Main.js#L1616 影响，`initQuickEdit()` 会因 `#mw-content-text` 的刷新而重新注入（比如在“交互式浏览历史”功能下），最明显的表现就是点 `#Wikiplus-Edit-TopBtn` ，对应的 MoeNotification 会弹两次。虽然最终编辑框只有一个，但这总归不是预期行为。所以我把 `#Wikiplus-Edit-TopBtn` 的 `onclick` 的事件监听注入环节放到了 https://github.com/Wikiplus/Wikiplus/blob/3b69dd219a3d499a14b6c32ca17bd3e802885015/src/Main.js#L951 里，把 `..Wikiplus-Edit-SectionBtn` 的点击事件先统统取消再重新监听（因为不好做判断）。

2021-07-30 00:00 UTC, AnYiLin commented
等等，想了想对 `.Wikiplus-Edit-SectionBtn` 的处理是不必要的，因为 `#mw-content-text ` 会刷新，最后只会有一个监听。但对 `#Wikiplus-Edit-TopBtn` 是有用的，它不在 `#mw-content-text `，监听会累积。稍后我再提一个 commit。

2021-08-19 03:01 UTC, AnYiLin commented
@Last-Order：新提了一个，以解决在Minerva上启用可视化编辑器之后match不到editURL里title的问题。

2021-08-19 16:02 UTC, Last-Order requested changes

2021-08-19 16:02 UTC, Last-Order commented on src/Main.js
> +                            var _sectionTargetName = function() {
没看出来搞一个函数的必要性，直接if一下就好了。另外请添加注释说明此处为何需要判断，为何需要隐藏`$('.mw-editsection-divider')`

2021-08-19 16:07 UTC, AnYiLin commented on src/Main.js
>                              var cloneNode = $(this).prev().clone();
在维基媒体项目上均可用，您原来的和我现在的方法都无法保证“在每个Wiki上都可用”。内部try catch之后还拿不到title会和原来一样抛出fail_to_init_quickedit。

2021-08-19 16:12 UTC, Last-Order commented on src/Main.js
>                              var cloneNode = $(this).prev().clone();
原先的写法与articlePath无关
`/wiki/`这个路径是可以拿到的，`mw.config.get("wgArticlePath")`，可以考虑取一下然后判断

2021-08-19 16:16 UTC, AnYiLin commented on src/Main.js
>                              var cloneNode = $(this).prev().clone();
判断的条件是？我不清楚其他Wiki启用可视化后是否也是这样，我甚至在萌娘上都没找到高级点儿的编辑器…更别说其他各种Wiki了。

2021-08-19 16:20 UTC, AnYiLin commented on src/Main.js
> +                            var _sectionTargetName = function() {
if的条件是？不隐藏是这样的https://z3.ax1x.com/2021/08/20/fLPkNQ.png，当然，这句可以不要，不是Wikiplus的问题。

2021-08-19 16:26 UTC, AnYiLin commented on src/Main.js
>                              var cloneNode = $(this).prev().clone();
换成new RegExp用mw.config.get("wgArticlePath") + ?拼一个正则也行，但感觉意义不大呢…

2021-08-19 16:27 UTC, Last-Order commented on src/Main.js
>                              var cloneNode = $(this).prev().clone();
```JavaScript
if (decodeURIComponent(editURL.match(/title=(.+?)&/))) {
    sectionTargetName = decodeURIComponent(editURL.match(/title=(.+?)&/)[1]);
} else {
    const articlePathPrefix = window.mw.config.get("wgArticlePath").replace("$1", "");
    const regex = new RegExp(`${articlePathPrefix}(.+?)\?`);
    if (regex.test(editURL)) {
        $('.mw-editsection-divider').css('visibility', 'hidden');
        sectionTargetName = decodeURIComponent(editURL.match(regex)[1]);
    } else {
        throwError('fail_to_init_quickedit');
    }
}
```

我意思是大概这样

2021-08-19 16:31 UTC, AnYiLin commented on src/Main.js
>                              var cloneNode = $(this).prev().clone();
这样也行，不过不能`if (decodeURIComponent(editURL.match(/title=(.+?)&/))) {`，`decodeURIComponent`返回的f出来都是真。

2021-08-19 16:32 UTC, Last-Order commented on src/Main.js
>                              var cloneNode = $(this).prev().clone();
嗯嗯对，随手写的复制粘贴错了（

2021-08-19 16:36 UTC, AnYiLin commented
啊对了，今晚维基QQ大群里有新人问怎么点快速编辑不出窗口，别人再转述问小群里的我
来来回回好一会儿，怎么说呢…建议用那个Moenotice前台提示一下用户不是非自确，不要只在控制台里报错…

2021-08-19 16:37 UTC, AnYiLin commented on src/Main.js
>                              var cloneNode = $(this).prev().clone();
那我白天的时候提一下新的。在master分支我就不用es6+了。

2021-08-20 02:42 UTC, merged